# Generated by Django 4.1.2 on 2024-10-16 23:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(db_column='idCategoria', max_length=4, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=80)),
                ('imagen', models.CharField(blank=True, max_length=400)),
                ('objetivo', models.CharField(max_length=20)),
                ('fechaCreacion', models.DateTimeField(default=datetime.datetime(2024, 10, 16, 20, 41, 8, 673900))),
                ('total_donado', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('fundador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='ongCrowndfunding.categoria')),
            ],
        ),
    ]
