# Generated by Django 4.1.2 on 2024-10-16 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongCrowndfunding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 20, 49, 7, 622746)),
        ),
    ]
