# Generated by Django 4.1.2 on 2024-10-16 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongCrowndfunding', '0003_alter_ong_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ong',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 20, 52, 29, 250571)),
        ),
        migrations.AlterField(
            model_name='ong',
            name='total_donado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
