# Generated by Django 4.1.2 on 2024-10-17 00:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ongCrowndfunding', '0006_alter_ong_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 22, 58, 234862)),
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 22, 58, 235860))),
                ('monto_donado', models.IntegerField()),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fundacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ongCrowndfunding.ong')),
            ],
        ),
    ]
