# Generated by Django 4.1.2 on 2024-10-17 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongCrowndfunding', '0007_alter_ong_fechacreacion_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ong',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 41, 40, 508444)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 41, 40, 508444)),
        ),
    ]
