# Generated by Django 4.1.2 on 2024-10-17 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongCrowndfunding', '0008_alter_ong_descripcion_alter_ong_fechacreacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='nombre_categoria',
        ),
        migrations.AlterField(
            model_name='ong',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 46, 41, 896560)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 46, 41, 897554)),
        ),
    ]
