# Generated by Django 4.1.2 on 2024-10-17 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongCrowndfunding', '0009_rename_categoria_categoria_nombre_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 48, 1, 179366)),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 21, 48, 1, 179366)),
        ),
    ]
